[FEATURE
PluginAndPartners/cart-woocommerce pull request #252
Opened 2021-06-10 13:47 UTC by felipeoliveiradev

2021-06-10 18:16 UTC, GiovanniCavallari commented on changelog.log
> +	- Rollout to Peru. This plugin is now supporting Peru, which core Basic Checkout, Custom Checkout, Tickets, and local language translations.
Desfazer alteração e voltar texto para 'includes'

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/payments/class-wc-woomercadopago-basic-gateway.php
> +			$fail_back_url_message = __( 'Choose the URL that we will show to your customers when we refuse their purchase. Make sure it core a message appropriate to the situation and give them useful inform
Desfazer alteração e voltar texto para 'includes'

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/module/class-wc-woomercadopago-configs.php
> +					'wc_woomercadopago_new_custom_gateway',
Não precisa ser adicionado.

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/module/class-wc-woomercadopago-configs.php
> +		$methods[] = 'WC_WooMercadoPago_New_Custom_Gateway';
Não precisa ser adicionado.

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/module/config/class-wc-woomercadopago-constants.php
> +		'WC_WooMercadoPago_New_Custom_Gateway',
Não precisa ser adicionado.

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/notification/class-wc-woomercadopago-notification-abstract.php
> +		add_action( 'woocommerce_api_mp_notification', array( $this, 'check_ipn_response') );
Remover rota.

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/notification/class-wc-woomercadopago-notification-abstract.php
> +	public function get_order_by_id( $id) {
Esse metodo nao ficou apenas na classe nova?

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/notification/class-wc-woomercadopago-notification-abstract.php
> +	public function get_order() {
Esse metodo nao ficou apenas na classe nova?

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/notification/class-wc-woomercadopago-notification-abstract.php
> +		if ( 'WC_WooMercadoPago_New_Custom_Gateway' === $used_gateway ) {
Não precisa ser adicionado.

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/payments/class-wc-woomercadopago-payment-abstract.php
> +		'WC_WooMercadoPago_New_Custom_Gateway',
Não precisa ser adicionado.

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/notification/class-wc-woomercadopago-notification-webhook.php
> +use Helpers\Cryptography as Cryptography;
Os helpers não precisam ser adicionados nessa class.

2021-06-10 18:16 UTC, GiovanniCavallari commented on core/notification/class-wc-woomercadopago-notification-webhook.php
> +			return $status;
Remover return.

2021-06-10 18:35 UTC, GiovanniCavallari commented on core/notification/class-wc-woomercadopago-notification-abstract.php
> +		$this->order   = get_order_by_id;
Remover atribuição.

2021-06-10 18:35 UTC, GiovanniCavallari commented on core/notification/class-wc-woomercadopago-notification-abstract.php
> +	public $order;
Remover atributo.

2021-06-14 13:20 UTC, lira requested changes
Só um ajustinho na tradução

2021-06-14 13:20 UTC, lira commented on i18n/languages/woocommerce-mercadopago-es_AR.po
> +msgid "Choose the URL that we will show to your customers when we refuse their purchase. Make sure it includes a  message appropriate to the situation and give them useful information so they can sol
Tem um espaço a mais, isso gera uma nova tradução, que não precisaria e está em todos os .po

2021-06-14 14:15 UTC, lira approved these changes

2021-06-14 14:15 UTC, merged