[PPWP-229] Updating Core Contract
PluginAndPartners/cart-woocommerce pull request #302
Opened 2021-09-02 14:37 UTC by FaraboliniMeli

**Changelog:**

- Core contract update with new fields.
- Some refactors on Get and Post Request functions, all verifications and the responsibility to build the response were removed to aside functions.
- Typo fix in request folder and class, was -> 'resquest'

2021-09-02 16:46 UTC, maicongouveia commented on includes/notification/new/class-wc-woomercadopago-notification.php
>  			if ( is_null($secret) || empty($secret) ) {
Eu acho que você pode remover esse cara daqui, pois você já esta fazendo essa validação dentro da outra função.

2021-09-02 20:30 UTC, maicongouveia approved these changes

2021-09-02 21:30 UTC, lira approved these changes

2021-09-03 12:37 UTC, maicongouveia requested changes

2021-09-03 12:37 UTC, maicongouveia commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +		if ( $this->secret_is_null_or_empty( $secret ) ) {
Não entendi escrever um função que tem quase o mesmo tamanho que o if dentro dela. Acho valido deixar apenas o if mesmo se ele só tem uma linha do que escrever mais uma função de 4 linhas, sendo que ele só se repete aqui neste caso.

2021-09-03 12:37 UTC, maicongouveia commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +	public function get_credentials() {
Acredito que essa função tambem não precise existir nesse contexto, se você esta utilizando ela apenas dentro do **assert_payload_hmac_is_valid**, porque não pegar a credencial la dentro pra validar em vez de instaciar uma função fora apenas para pegar o valor da variavel fora para colocar ela dentro de novo da função?

2021-09-03 12:37 UTC, maicongouveia commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +				if ( ! $this->valid_get_payload( $data ) ) {
Vai estourar um erro pois você comentou a função no código

2021-09-03 12:37 UTC, maicongouveia commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +				if ( $this->valid_post_payload( $data ) ) {
Vai estourar um erro pois você comentou a função no código

2021-09-03 12:37 UTC, maicongouveia commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +	public function valid_get_payload( $data ) {
Não acho que seja necessário validar se todos os campos vieram se não utilizamos todos eles. Acho valido apenas verificar aqueles que usamos para efetuar as consultas.

2021-09-03 12:37 UTC, maicongouveia commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +	public function valid_post_payload( $data ) {
Não acho que seja necessário validar se todos os campos vieram se não utilizamos todos eles. Acho valido apenas verificar aqueles que usamos para efetuar as consultas e alterações no pedido.

2021-09-03 12:37 UTC, maicongouveia commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +	public function build_get_response( $order ) {
Porque não colocar a geração do HMAC dentro dessa função, já que ela esta lidando com o response?

2021-09-03 12:37 UTC, maicongouveia commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +	public function build_post_response( $data, $order ) {
Porque não colocar a geração do HMAC dentro dessa função, já que ela esta lidando com o response?

2021-09-03 12:55 UTC, FaraboliniMeli commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +	public function valid_get_payload( $data ) {
É exatamente o todo que eu coloquei.

2021-09-03 12:55 UTC, FaraboliniMeli commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +	public function valid_post_payload( $data ) {
É exatamente o todo que eu coloquei

2021-09-03 12:58 UTC, FaraboliniMeli commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +		if ( $this->secret_is_null_or_empty( $secret ) ) {
Fiz a função só pela legibilidade do código, quem chegar de fora entende mais fácil o fluxo.

2021-09-03 13:06 UTC, FaraboliniMeli commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +	public function get_credentials() {
Resuo de código, se eventualmente precisarmos de access token em outros lugares fica mais fácil chamar a funçao do que instanciar uma classe e chamar uma função dessa classe em todos os lugares que formos usar. Eu uso essa funçao  no **get_order** e no **post_order** para verificar o hmac que o Core mandou para gente e criar o novo hmac, no **assert_payload_hmac_is_valid** eu apenas verifico que ele não veio nulo e nem vazio.

2021-09-03 13:14 UTC, FaraboliniMeli commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +	public function build_post_response( $data, $order ) {
Deixei a parte de gerar o HMAC de fora dos métodos que montam a response só para ficar mais visível que geramos um novo HMAC de acordo com a response e voltamos para o Core, por ser chamada de um método estático não "polui" o código e mantém a responsabilidade do endpoint da loja, que é gerar um novo hmac para o Core.

2021-09-03 13:15 UTC, FaraboliniMeli commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +				if ( $this->valid_post_payload( $data ) ) {
Vou remover o comentário da função toda!!

2021-09-03 13:15 UTC, FaraboliniMeli commented on includes/notification/new/class-wc-woomercadopago-notification.php
> +				if ( ! $this->valid_get_payload( $data ) ) {
Vou remover o comentário da função toda!!

2021-09-03 13:28 UTC, maicongouveia approved these changes

2021-09-03 13:34 UTC, merged