Feature/ppwp 417/paycash
PluginAndPartners/cart-woocommerce pull request #343
Opened 2021-11-04 14:33 UTC by cleitonaguiarandrade

- Adicionados pagamentos paycash no checkout ticket.

2021-11-04 14:42 UTC, cleitonaguiarandrade commented
<img width="434" alt="Captura de Tela 2021-11-04 às 11 36 16" src="https://user-images.githubusercontent.com/80361051/140334596-ae03f194-1e84-4a29-8466-e6af643d4f2a.png">

2021-11-04 18:03 UTC, luiztucillo requested changes

2021-11-04 18:03 UTC, luiztucillo commented on templates/checkout/ticket-checkout.php
> +															<input type="radio" class="mp-form-control-check" name="mercadopago_ticket[paymentMethodId]" id="<?php echo esc_attr($payment['id']); ?>" value="<?php echo esc_attr($payment['id'] . '|
Aqui você usaria aquela classe tbm pra garantir a consistencia:
```php
<input ... value="<?php echo esc_attr((new WC_WooMercadoPago_Composite_Id_Helper())-> generateIdFromPlace($payment['id'], $place['payment_option_id'])); ?>"...
```

2021-11-04 18:43 UTC, lira commented on includes/module/preference/class-wc-woomercadopago-preference-ticket.php
> +		$explode_payment_method_id              = explode('|', $ticket_checkout['paymentMethodId']);
Ahh precisa mudar o return para return $this->parse(...), senão ele vai procurar uma função parse no PHP. 😁

2021-11-05 18:42 UTC, lira approved these changes

2021-11-05 19:04 UTC, luiztucillo requested changes

2021-11-05 19:21 UTC, DouglasCorreiaMeli commented on includes/payments/class-wc-woomercadopago-ticket-gateway.php
> +				'label'             => 'paycash' === strtolower($payment_method_ticket['name']) ? 'PayCash (Soriana, Extra, 7-Eleven, Calimax e Circle K)' : $payment_method_ticket['name'],
alteração removida para entrar no próximo pull request

2021-11-05 19:23 UTC, luiztucillo approved these changes

2021-11-05 20:10 UTC, lira approved these changes

2021-11-05 20:23 UTC, merged